# -*- coding: utf-8 -*-
"""Personal library manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z82l1lJdvC9MEirWk-kCzEC1DUFzY_hG

#personal library manager
"""

import streamlit as st

# Title of the app
st.title("Personal Library Manager")

# Initialize a book list (you could also use a database for this in a real app)
if 'books' not in st.session_state:
    st.session_state.books = []

# Add Book section
st.header("Add a New Book")
book_title = st.text_input("Enter book title")
book_author = st.text_input("Enter book author")
book_genre = st.text_input("Enter book genre")

# Function to add a book
def add_book():
    if book_title and book_author and book_genre:
        st.session_state.books.append({
            'title': book_title,
            'author': book_author,
            'genre': book_genre
        })
        st.success("Book added successfully!")
    else:
        st.error("Please fill all fields.")

if st.button("Add Book"):
    add_book()

# View All Books section
st.header("All Books")
if st.session_state.books:
    for book in st.session_state.books:
        st.write(f"Title: {book['title']}, Author: {book['author']}, Genre: {book['genre']}")
else:
    st.write("No books added yet.")

# Search for Books section
st.header("Search for a Book")
search_query = st.text_input("Search by title or author")

if search_query:
    filtered_books = [book for book in st.session_state.books if search_query.lower() in book['title'].lower() or search_query.lower() in book['author'].lower()]
    if filtered_books:
        for book in filtered_books:
            st.write(f"Title: {book['title']}, Author: {book['author']}, Genre: {book['genre']}")
    else:
        st.write("No books found with that query.")

# Remove a Book section
st.header("Remove a Book")
book_to_remove = st.selectbox("Select a book to remove", [book['title'] for book in st.session_state.books])

if st.button("Remove Book"):
    st.session_state.books = [book for book in st.session_state.books if book['title'] != book_to_remove]
    st.success("Book removed successfully!")
